services:
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5432:5432'
  pruebahexagonal:
    build: .
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
        - 'DB_NAME=${DB_NAME}'
        - 'DB_USER=${DB_USER}'
        - 'DB_PASSWORD=${DB_PASSWORD}'
        - 'DB_JPA_USER=${DB_JPA_USER}'
        - 'DB_JPA_PASSWORD=${DB_JPA_PASSWORD}'
        - 'SPRING_PROFILES_ACTIVE=prod'